create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text,
  phone text,
  department text,
  institution text,
  organization text,
  supervisor text,
  start_date date,
  end_date date,
  profile_image_path text,
  role text not null default 'student' check (role in ('student', 'admin'))
);

create table public.activities (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_date date not null,
  activity text not null,
  description text not null,
  image_path text,
  status text not null default 'Pending' check (status in ('Pending', 'Approved', 'Rejected')),
  created_at timestamptz not null default now()
);

create table public.activity_reviews (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.activities(id) on delete cascade,
  reviewer_id uuid not null references auth.users(id) on delete cascade,
  comment text,
  status text not null check (status in ('Approved', 'Rejected')),
  reviewed_at timestamptz not null default now()
);

create table public.organizations (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  supervisor text
);

alter table public.profiles
  add column organization_id bigint references public.organizations(id) on delete set null;

create unique index organizations_name_lower_uidx
  on public.organizations (lower(name));

alter table public.profiles enable row level security;
alter table public.activities enable row level security;
alter table public.activity_reviews enable row level security;
alter table public.organizations enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role = 'admin'
  );
$$;

create policy "Students can view their profile"
  on public.profiles for select using (auth.uid() = id);

create policy "Students can update their profile"
  on public.profiles for update using (auth.uid() = id);

create policy "Students can view their activities"
  on public.activities for select using (auth.uid() = user_id);

create policy "Students can create their activities"
  on public.activities for insert with check (auth.uid() = user_id);

create policy "Students can update their activities"
  on public.activities for update using (auth.uid() = user_id);

create policy "Students can delete their activities"
  on public.activities for delete using (auth.uid() = user_id);

create policy "Students can view reviews for their activities"
  on public.activity_reviews for select using (
    exists (
      select 1 from public.activities
      where activities.id = activity_reviews.activity_id
        and activities.user_id = auth.uid()
    )
  );

create policy "Admins can view all profiles"
  on public.profiles for select using (public.is_admin());

create policy "Admins can view all activities"
  on public.activities for select using (public.is_admin());

create policy "Admins can view all reviews"
  on public.activity_reviews for select using (public.is_admin());

create policy "Admins can create reviews"
  on public.activity_reviews for insert with check (public.is_admin() and auth.uid() = reviewer_id);

create policy "Admins can update activity status"
  on public.activities for update using (public.is_admin());

create policy "Authenticated users can view organizations"
  on public.organizations for select using (auth.uid() is not null);
