import { useState } from 'react'
import { Status } from '../components/UI.jsx'

export default function ReviewActivity({ activity, onBack, onReview, saving }) {
  const [comment, setComment] = useState('')
  if (!activity) return null

  const submitReview = (status) => onReview(activity.id, status, comment)

  return <div className="content narrow"><div className="page-intro"><div className="review-student">{activity.studentAvatarUrl ? <img className="review-student-avatar" src={activity.studentAvatarUrl} alt="" /> : <span className="review-student-avatar">{activity.studentName.slice(0, 1).toUpperCase()}</span>}<div><p>{activity.studentEmail}</p><h2>{activity.title}</h2></div></div><Status status={activity.status} /></div><section className="review-detail"><dl><div><dt>Activity date</dt><dd>{new Date(`${activity.date}T00:00:00`).toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })}</dd></div><div><dt>Student</dt><dd>{activity.studentName}</dd></div></dl><h3>Student notes</h3><p className="review-description">{activity.description}</p>{activity.imageUrl ? <a className="activity-image-link" href={activity.imageUrl} target="_blank" rel="noreferrer"><img className="review-activity-image" src={activity.imageUrl} alt={`Attachment for ${activity.title}`} /><span>Open full-size image ↗</span></a> : <p className="file-hint">No image attached to this activity.</p>}{activity.reviews?.length > 0 && <div className="review-history"><h3>Previous reviews</h3>{activity.reviews.map((review) => <article key={review.id}><Status status={review.status} /><time>{new Date(review.reviewed_at).toLocaleDateString()}</time>{review.comment && <p>{review.comment}</p>}</article>)}</div>}{activity.status === 'Pending' && <label className="review-comment">Review comment<textarea value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Optional feedback for the student" /></label>}<div className="form-actions"><button className="button button-light" onClick={onBack}>Back to reviews</button>{activity.status === 'Pending' && <><button className="button button-light" disabled={saving} onClick={() => submitReview('Rejected')}>Reject</button><button className="button button-dark" disabled={saving} onClick={() => submitReview('Approved')}>{saving ? 'Saving...' : 'Approve activity'} <span>→</span></button></>}</div></section></div>
}